import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Notification from "./components/Notification";
import Nav from "./components/Nav";
import Footer from "./components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "MIMOSA",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className + " no-scrollbar"}>
        <Notification />
        <Nav />
        {children}
        <Footer />
      </body>
    </html>
  );
}
